import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "../styles/globals.css";
import clsx from "clsx";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter"
});

const oswald = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, oswald.variable)}>{children}</body>
    </html>
  );
}
